<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>CyberFeedForward.TheMadArchivist</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <PublishProfile Condition="'$(Platform)' != '' and '$(Platform)' != 'AnyCPU'">win-$(Platform).pubxml</PublishProfile>
    <UseWinUI>true</UseWinUI>
    <WinUISDKReferences>false</WinUISDKReferences>
    <EnableMsixTooling>true</EnableMsixTooling>
    <WindowsAppSdkDeploymentManagerInitialize>false</WindowsAppSdkDeploymentManagerInitialize>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Platform)' == '' or '$(Platform)' == 'AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AppPackages\**" />
    <Compile Remove="Assets\Images\**" />
    <Compile Remove="Contracts\**" />
    <Compile Remove="Helpers\**" />
    <Content Remove="Assets\Images\**" />
    <EmbeddedResource Remove="AppPackages\**" />
    <EmbeddedResource Remove="Assets\Images\**" />
    <EmbeddedResource Remove="Contracts\**" />
    <EmbeddedResource Remove="Helpers\**" />
    <None Remove="AppPackages\**" />
    <None Remove="Assets\Images\**" />
    <None Remove="Contracts\**" />
    <None Remove="Helpers\**" />
    <Page Remove="AppPackages\**" />
    <Page Remove="Assets\Images\**" />
    <Page Remove="Contracts\**" />
    <Page Remove="Helpers\**" />
  </ItemGroup>
  <ItemGroup>
    <Content Remove="Assets\AppIcon.altform-lightunplated_targetsize-16.png" />
    <Content Remove="Assets\AppIcon.altform-lightunplated_targetsize-24.png" />
    <Content Remove="Assets\AppIcon.altform-lightunplated_targetsize-256.png" />
    <Content Remove="Assets\AppIcon.altform-lightunplated_targetsize-32.png" />
    <Content Remove="Assets\AppIcon.altform-lightunplated_targetsize-48.png" />
    <Content Remove="Assets\AppIcon.altform-unplated_targetsize-16.png" />
    <Content Remove="Assets\AppIcon.altform-unplated_targetsize-24.png" />
    <Content Remove="Assets\AppIcon.altform-unplated_targetsize-256.png" />
    <Content Remove="Assets\AppIcon.altform-unplated_targetsize-32.png" />
    <Content Remove="Assets\AppIcon.altform-unplated_targetsize-48.png" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Assets\AppIcon.scale-100.png" />
    <None Remove="Assets\AppIcon.scale-125.png" />
    <None Remove="Assets\AppIcon.scale-150.png" />
    <None Remove="Assets\AppIcon.scale-200.png" />
    <None Remove="Assets\AppIcon.scale-400.png" />
    <None Remove="Assets\AppIcon.targetsize-16.png" />
    <None Remove="Assets\AppIcon.targetsize-16_altform-lightunplated.png" />
    <None Remove="Assets\AppIcon.targetsize-16_altform-unplated.png" />
    <None Remove="Assets\AppIcon.targetsize-24.png" />
    <None Remove="Assets\AppIcon.targetsize-24_altform-lightunplated.png" />
    <None Remove="Assets\AppIcon.targetsize-24_altform-unplated.png" />
    <None Remove="Assets\AppIcon.targetsize-256.png" />
    <None Remove="Assets\AppIcon.targetsize-256_altform-lightunplated.png" />
    <None Remove="Assets\AppIcon.targetsize-256_altform-unplated.png" />
    <None Remove="Assets\AppIcon.targetsize-32.png" />
    <None Remove="Assets\AppIcon.targetsize-32_altform-lightunplated.png" />
    <None Remove="Assets\AppIcon.targetsize-32_altform-unplated.png" />
    <None Remove="Assets\AppIcon.targetsize-48.png" />
    <None Remove="Assets\AppIcon.targetsize-48_altform-lightunplated.png" />
    <None Remove="Assets\AppIcon.targetsize-48_altform-unplated.png" />
    <None Remove="Assets\BadgeLogo.scale-100.png" />
    <None Remove="Assets\BadgeLogo.scale-125.png" />
    <None Remove="Assets\BadgeLogo.scale-150.png" />
    <None Remove="Assets\BadgeLogo.scale-200.png" />
    <None Remove="Assets\BadgeLogo.scale-400.png" />
    <None Remove="Assets\LargeTile.scale-100.png" />
    <None Remove="Assets\LargeTile.scale-125.png" />
    <None Remove="Assets\LargeTile.scale-150.png" />
    <None Remove="Assets\LargeTile.scale-200.png" />
    <None Remove="Assets\LargeTile.scale-400.png" />
    <None Remove="Assets\MediumTitle.scale-100.png" />
    <None Remove="Assets\MediumTitle.scale-125.png" />
    <None Remove="Assets\MediumTitle.scale-150.png" />
    <None Remove="Assets\MediumTitle.scale-200.png" />
    <None Remove="Assets\MediumTitle.scale-400.png" />
    <None Remove="Assets\PackageLogo.scale-100.png" />
    <None Remove="Assets\PackageLogo.scale-125.png" />
    <None Remove="Assets\PackageLogo.scale-150.png" />
    <None Remove="Assets\PackageLogo.scale-200.png" />
    <None Remove="Assets\PackageLogo.scale-400.png" />
    <None Remove="Assets\SmallTile.scale-100.png" />
    <None Remove="Assets\SmallTile.scale-125.png" />
    <None Remove="Assets\SmallTile.scale-150.png" />
    <None Remove="Assets\SmallTile.scale-200.png" />
    <None Remove="Assets\SmallTile.scale-400.png" />
    <None Remove="Assets\SplashScreen.scale-100.png" />
    <None Remove="Assets\SplashScreen.scale-125.png" />
    <None Remove="Assets\SplashScreen.scale-150.png" />
    <None Remove="Assets\SplashScreen.scale-200.png" />
    <None Remove="Assets\SplashScreen.scale-400.png" />
    <None Remove="Assets\WideTitle.scale-100.png" />
    <None Remove="Assets\WideTitle.scale-125.png" />
    <None Remove="Assets\WideTitle.scale-150.png" />
    <None Remove="Assets\WideTitle.scale-200.png" />
    <None Remove="Assets\WideTitle.scale-400.png" />
  </ItemGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <!--
    Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
    Tools extension to be activated for this project even if the Windows App SDK Nuget
    package has not yet been restored.
  -->
  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.1839" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.1.3" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Models\" />
    <Folder Include="Converters\" />
    <Folder Include="Services\" />
    <Folder Include="ViewModels\Pages\" />
    <Folder Include="Views\Pages\" />
  </ItemGroup>
  <PropertyGroup>
    <ShellExtensionPlatform>$(Platform)</ShellExtensionPlatform>
    <ShellExtensionPlatform Condition="'$(Platform)' == '' or '$(Platform)' == 'AnyCPU'">x64</ShellExtensionPlatform>
    <ShellExtensionPlatform Condition="'$(Platform)' == 'ARM64'">x64</ShellExtensionPlatform>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZeeMadArchivist.ShellExtension\ZeeMadArchivist.ShellExtension.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <Private>false</Private>
      <Properties>Platform=$(ShellExtensionPlatform);Configuration=$(Configuration)</Properties>
      <SetTargetFramework>TargetFramework=net48</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Include="..\AppTools\AppTools.csproj" />
    <ProjectReference Include="..\CyberFeedForward.Tools.ZeeFileSystem\CyberFeedForward.Tools.ZeeFileSystem.csproj" />
    <Content Include="..\ZeeMadArchivist.ShellExtension\bin\$(ShellExtensionPlatform)\$(Configuration)\ZeeMadArchivist.ShellExtension.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\AppTools\Icons\**\*.*" TargetPath="Icons\%(RecursiveDir)%(Filename)%(Extension)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <!--
    Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution
    Explorer "Package and Publish" context menu entry to be enabled for this project even if
    the Windows App SDK Nuget package has not yet been restored.
  -->
  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>

  <!-- Publish Properties -->
  <PropertyGroup>
    <PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
    <PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">True</PublishReadyToRun>
    <PublishTrimmed Condition="'$(Configuration)' == 'Debug'">False</PublishTrimmed>
    <PublishTrimmed Condition="'$(Configuration)' != 'Debug'">True</PublishTrimmed>
    <AssemblyTitle>Zee Mad Archivist</AssemblyTitle>
    <GenerateTemporaryStoreCertificate>True</GenerateTemporaryStoreCertificate>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <GenerateAppInstallerFile>False</GenerateAppInstallerFile>
    <AppxPackageSigningEnabled>False</AppxPackageSigningEnabled>
    <AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
    <AppxAutoIncrementPackageRevision>True</AppxAutoIncrementPackageRevision>
    <GenerateTestArtifacts>False</GenerateTestArtifacts>
    <AppxBundle>Never</AppxBundle>
    <HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PRIResource Remove="AppPackages\**" />
  </ItemGroup>
  <ItemGroup>
    <PRIResource Remove="Helpers\**" />
  </ItemGroup>
  <ItemGroup>
    <PRIResource Remove="Contracts\**" />
  </ItemGroup>
  <ItemGroup>
    <PRIResource Remove="Assets\Images\**" />
  </ItemGroup>
  <ItemGroup>
    <Content Remove="..\AppTools\Icons\Downloads.ico" />
    <Content Remove="..\AppTools\Icons\Folder.ico" />
    <Content Remove="..\AppTools\Icons\Music.ico" />
    <Content Remove="..\AppTools\Icons\Pictures.ico" />
    <Content Remove="..\AppTools\Icons\Tutorials.ico" />
  </ItemGroup>
</Project>